apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-app-satr
spec:
  environments:
    - name: development
      build:
        from: main
    - name: prod
      build:
        from: release
  components:
    - name: server
      src: ./backend
      ports:
        - name: http
          port: 3000
      variables:
        PORT: 3000
        VAR1:
        VAR2: "common value"
      environmentConfig:
        - environment: development
          variables:
            VAR1: "set in dev2"
            VAR_IN_DEV: "var in dev only2"
        - environment: prod
          variables:
            VAR2: "overriden in prod2"
            VAR_IN_PROD: "var in prod only2"
    - name: www
      src: ./frontend
      ports:
        - name: http
          port: 3007
      publicPort: http
      variables:
        PORT: 3007
        ECHO_URL: "http://server:3000"
      environmentConfig:
        - environment: development
          replicas: 2
        - environment: prod
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 5
          variables:
            NODE_ENV: production
  dnsAppAlias:
    environment: prod
    component: www
